version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
     - 1883:1883
  pyro-ns:
    build: pyro-ns
    # image: farshidtz/pyro4-ns
    # ports: ["9090-9091:9090-9091"]
    command: ["--host=pyro-ns"]
  python-agent:
    build: training
    depends_on:
     - pyro-ns
    volumes:
     - ./training/model:/model
    # ports: ["9100:9100"]
    command: ["--bname=Agent", "--bpath=agent/agent.py", "--rname=python-agent-0", "--host=python-agent", "--port=9100", "--ns"]
  dpa:
    build: data-processing-agent
    links:
     - pyro-ns
     - python-agent
     - mosquitto
    volumes:
     - ./data-processing-agent/config:/config
    ports:
     - "8319:8319"
    environment:
     - connection_broker_mqtt_hostname=mosquitto
     - ceml_init_bootstrapping=/config/statement.json
    entrypoint: bash -c "dockerize -wait tcp://python-agent:9100 &&
      java -cp ./*:/dependencies/* org.springframework.boot.loader.PropertiesLauncher"
